### PR TITLE
Target netstandard instead of full .NET

### PR DESCRIPTION
**Pull request by nphmuller**
Targetting .NET Standard has the benefit that this library can be used by any platform that supports that version. (Personally I'm trying to use the library on .NET Core 2.0.)

I choose to target version 1.3, because it's the first version that was easy to implement without any additional dependencies and big code changes. The only problem with version 1.3 is that .NET Full 4.6 is the first version that supports it, breaking earlier compatibility with .NET Full 4.5. .NET Full 4.5 is not supported by Microsoft anymore though.

See: https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

I also had to update the csproj files, because the old version didn't support .NET Standard targets. This means the project can only be opened from Visual Studio 2017+. VS2017 Community Edition is free though, so it shouldn't be that big a problem.

### CODE REVIEW

**Comment by nphmuller** [comment]
Seems the build fails (no support for the new csproj files). Don't think I can fix that, right?

By the way, I've ran the unit tests on my own machine and they all succeed.

**Comment by nphmuller** [comment]
@raynjamin @paulstraw 
Sorry for being so pushy (only a week has passed), but would you mind looking at this PR?
This issue is the only thing blocking us from moving to .NET Core.

We could deploy my fork with the fix to our private NuGet feed. But of course we'd prefer just using the official feed, as that would simplify things a lot.

**Comment by paulstraw** [comment]
@nphmuller I no longer work at imgix or have permissions to merge PRs into this repo, sorry.

**Comment by nphmuller** [comment]
@paulstraw No problem. Sorry for @‘ing you!

**Comment by raynjamin** [comment]
@nphmuller thanks for your contribution.

**Comment by nphmuller** [comment]
@raynjamin No problem. Thanks for maintaining this project. Takes way more effort! 👍

**Comment by nphmuller** [comment]
@raynjamin When are your planning to release the new version to NuGet?

**Comment by raynjamin** [comment]
@nphmuller 5 minutes ago.

**Comment by nphmuller** [comment]
Yay. Thank you!

**Comment by nphmuller** [comment]
@raynjamin Seems the new package format requires the Cryptocraphy dll to be published as a seperate NuGet packages. Which seems a bit excessive considering the purpose.

This means currently the library cannot be used since 1.0.1, since the cryptocraphy package doesn't exist on NuGet.

I've created a PR to just include the crypto source file in the main library. This means there's 1 dll (imgix-csharp.dll) instead of 2. See: https://github.com/raynjamin/Imgix-CSharp/pull/9

**Comment by raynjamin** [comment]
Interesting. My apologies, this whole process has changed dramatically since I last published a package. 

I don't think the answer is to pull `Crc32.cs` into the ImgixClient project. I'll look into this and get back to you.

**Comment by nphmuller** [comment]
No problem. I agree that it’s probably not the best solution.

Think this is the problem you ran into: (maybe you’re not using dotnet cli, but the underlying problem sounds the same) https://github.com/dotnet/cli/issues/3959

**Pull request merged**
